<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Loom.Analyzer\Loom.Analyzer.csproj" />
    <ProjectReference Include="..\Loom.Common\Loom.Common.csproj" />
    <ProjectReference Include="..\Loom.Parser\Loom.Parser.csproj" />
  </ItemGroup>

</Project>
